INSERT INTO lender (first_name, last_name, username, bio) VALUES
('Susie', 'Anderson', 'books4ever', 'Some people aim to save neglected pets. I aim to save neglected houseplants. Buffalo, NY resident, I know the importance of keeping plants alive indoors -- especially since, here in the Northeast U.S., we don’t get to see much plant life outside during winter. I must say, it’s a noble act; sacrificing a book lender bio front-loaded with accomplishments, for the sake of our forgetful nature and thirsty houseplants.'),
('Twila', 'Hilt', 'scififuture', 'Harry Potter fans, rejoice -- or cower in fear. He-Who-Must-Not-Be-Named has a book lender account, and she''s not afraid to share her truth -- in the form of a clever use of Christina Perri lyrics.'),
('Ola', 'Shimbe', 'toots', 'Ola is famous and well-known for winning the Pullet’s Surprise, the No Bell Piece Prize, and the Mack Arthur Genie Grant for her poetry collection exploring the uncertainty of scales, The Waistland. The Waistland is a corset of sonnets dealing with the tragic difficulty of being a size 14 in a world of zeros. Kellian received her MFA from the I-Owe-ya Writers Workshop. She currently lives with her wild emu, Walt, in the Northwest.'),
('Frank', 'Wallace', 'amalgamation21', 'Frank has been awarded the Emily Dickinson accolade for his upcoming work titled, “I am so old”. At age 32, this will be his first award for poetry; however as a teenager he received a bronze certificate for his entry into the middle school song contest. Mister Wallace is most well known for his attempt to break the world record for typing out the letter P on a keyboard; however, after 5,328,685 times, he collapsed muttering “I need to pee”.'),
('Tyler', 'Walters', 'deus_ex', 'Tyler Walters was intended to be the reincarnation of Robert Lowell but owing to a clerical error is actually the reincarnation of John Berryman. His poetry is quite remarkable and is easily the best on his ward. He is currently writing an opera about oranges and in his next life he wants to be a Shakespearean villain. His latest collection ‘In conversation with Kilgore Trout’ has attracted wide praise and is available in spirit everywhere.'),
('Bill', 'Smith', 'book_monger', 'Bill Pinkyring Moses de la Salle Cuthbert-Smith is that weird guy who lives in the van parked across the street from your house. He is allergic to everything, especially air and water. His most recently read book, the title of which is unpronounceable in any human language, was at the top of the best seller list in the Autonomous Republic of Erewhon.'),
('Frank', 'Allen', 'tonberry_24', 'Frank Allen, the once promising young reader, has decided after reading many literary journals, that mediocrity is the way to go. Obviously no one was brilliant enough to understand his allusions to the classical mythologies of ancient civilizations, his personal theories of metaphysics, or his unique insight into the human condition.'),
('Millie', 'Simmons', 'twelve_books', 'Millie Simmons just finished reading “Apathy: A 21st Century Manifesto”. She’d tell you more about herself if she could be bothered.');
